name: webshine
description: A Lightweight interceptor for dio, allowing you to sniff traffic
version: 0.1.0-dev.3
homepage: "https://github.com/meg4cyberc4t/webshine"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  dio: ^5.1.2
  flutter:
    sdk: flutter
  freezed: ^2.3.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.2
  json_serializable: ^6.6.2
